plugins {
    id 'maven-publish'
	id 'fabric-loom' version '1.18-SNAPSHOT'
	id 'ploceus' version '1.18-SNAPSHOT'
}

repositories {
    maven {
        url "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        url "https://maven.taumc.org/releases"
    }
    mavenCentral()
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

ploceus {
    setIntermediaryGeneration(2)
}

configurations {
    shadow {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings ploceus.featherMappings(project.feather_build)
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "com.velocitypowered:velocity-native:3.4.0-SNAPSHOT"
    include "com.velocitypowered:velocity-native:3.4.0-SNAPSHOT"

    compileOnly "io.netty:netty-all:4.2.18.Final"
    shadow "io.netty:netty-all:4.2.18.Final"

    modCompileOnly "org.embeddedt.celeritas:celeritas-common:${project.celeritas_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

// ensure that the encoding is set to UTF-8, no matter what the system default is
// this fixes some edge cases with special characters not displaying correctly
// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from "LICENSE"
    archiveBaseName = "iungere"
    archiveVersion = "1.0.0"
    from({ configurations.shadow.collect { zipTree(it) } }) {
        exclude "META-INF", "META-INF/**"
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

remapJar {
    archiveBaseName = "iungere"
    archiveVersion = "1.0.0"
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }
}

/*afterEvaluate {
    tasks.getByName("configureClientLaunch").doFirst {
        loom {
            runs {
                all {
                    property("fabric.development=true")
                    property("mixin.hotSwap")
                    // vmArg("-javaagent:${dependencies.module(group = "net.fabricmc", name = "sponge-mixin")}")
                    def mixinJarFile = configurations.compileClasspath.files {
                        it.group == "net.fabricmc" && it.name == "sponge-mixin"
                    }.find { true }
                    vmArg("-javaagent:$mixinJarFile")

                    ideConfigGenerated = true
                }
            }
        }
    }
}*/
